
import { useEffect,useMemo,useState } from 'react';
import { supabase } from '../lib/supabaseClient';
import * as XLSX from 'xlsx';
const money=v=>'$'+Math.round(Number(v||0)).toLocaleString('es-AR'), num=v=>Number(v||0), today=()=>new Date().toISOString().slice(0,10);
const nums=['superficie_ha','costo_alquiler_ha','hectareas','toneladas','precio_estimado','cantidad_por_ha','costo_unitario','cantidad','precio','precio_tn','cabezas','peso_inicial_kg','peso_final_kg','dias_ciclo','costo_total','kilos_vendidos','precio_kg','comision','flete','stock_minimo','precio_promedio','cantidad_total'];
export default function Home(){
 const [session,setSession]=useState(null),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[msg,setMsg]=useState(''),[tab,setTab]=useState('dashboard'),[edit,setEdit]=useState(null);
 const [empresaId,setEmpresaId]=useState(''),[campaniaId,setCampaniaId]=useState(''),[loteId,setLoteId]=useState('');
 const [empresas,setEmpresas]=useState([]),[campanias,setCampanias]=useState([]),[lotes,setLotes]=useState([]),[prodAgri,setProdAgri]=useState([]),[costosAgri,setCostosAgri]=useState([]),[ventasAgri,setVentasAgri]=useState([]),[stockCultivos,setStockCultivos]=useState([]),[insumos,setInsumos]=useState([]),[movInsumos,setMovInsumos]=useState([]),[prodGan,setProdGan]=useState([]),[costosGan,setCostosGan]=useState([]),[ventasGan,setVentasGan]=useState([]);
 const [empresa,setEmpresa]=useState({nombre:'Mi empresa',pais:'Argentina',provincia:'',localidad:''});
 const [campania,setCampania]=useState({nombre:'2025/2026',fecha_inicio:'',fecha_fin:'',estado:'activa'});
 const [lote,setLote]=useState({nombre:'Lote 1',campo:'',superficie_ha:0,provincia:'',localidad:'',tenencia:'propio',costo_alquiler_ha:0,cultivo_actual:'Soja'});
 const [pa,setPa]=useState({fecha:today(),cultivo:'Soja',hectareas:0,rinde_esperado_qq_ha:0,rinde_real_qq_ha:0,toneladas:0,precio_estimado:0,observaciones:''});
 const [ca,setCa]=useState({fecha:today(),cultivo:'Soja',categoria:'Herbicida',concepto:'',cantidad_por_ha:0,costo_unitario:0,hectareas:0,unidad:'lt',moneda:'ARS',proveedor:'',forma_pago:'',observaciones:''});
 const [va,setVa]=useState({fecha:today(),cultivo:'Soja',cantidad:0,unidad:'tn',toneladas:0,precio:0,precio_tn:0,moneda:'ARS',comprador:'',condicion:'',estado:'pendiente'});
 const [sc,setSc]=useState({cultivo:'Soja',cantidad_total:0,unidad:'tn',precio_promedio:0,observaciones:''});
 const [insumo,setInsumo]=useState({nombre:'',tipo:'Herbicida',unidad:'litros',marca:'',proveedor:'',stock_minimo:0,observaciones:''});
 const [movIns,setMovIns]=useState({fecha:today(),insumo_id:'',tipo_movimiento:'compra',cantidad:0,costo_unitario:0,cultivo:'',motivo:'',observaciones:''});
 const [pg,setPg]=useState({fecha:today(),categoria:'Recría',potrero:'',cabezas:0,peso_inicial_kg:0,peso_final_kg:0,dias_ciclo:0});
 const [cg,setCg]=useState({fecha:today(),categoria:'Cría',tipo_costo:'Sanidad',concepto:'',costo_total:0,cabezas:0,moneda:'ARS',proveedor:'',observaciones:''});
 const [vg,setVg]=useState({fecha:today(),categoria:'Novillos',cabezas:0,kilos_vendidos:0,precio_kg:0,comprador:'',comision:0,flete:0,moneda:'ARS'});
 useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data.session));const {data:l}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>l.subscription.unsubscribe()},[]);
 useEffect(()=>{if(session)cargar()},[session]); useEffect(()=>{if(empresaId)cargar()},[empresaId]);
 async function ingresar(){let {error}=await supabase.auth.signInWithPassword({email,password}); setMsg(error?error.message:'Ingreso correcto.')}
 async function registrar(){let {error}=await supabase.auth.signUp({email,password}); setMsg(error?error.message:'Usuario creado. Revisá email si pide confirmación.')}
 async function salir(){await supabase.auth.signOut();setSession(null)}
 async function cargar(){
  const emp=await supabase.from('empresas').select('*').order('created_at',{ascending:false}); setEmpresas(emp.data||[]);
  const eid=empresaId||emp.data?.[0]?.id||''; if(eid&&!empresaId)setEmpresaId(eid); if(!eid)return;
  const qs=[['campanias',setCampanias],['lotes',setLotes],['produccion_agricola',setProdAgri],['costos_agricolas',setCostosAgri],['ventas_agricolas',setVentasAgri],['stock_cultivos',setStockCultivos],['insumos',setInsumos],['movimientos_insumos',setMovInsumos],['produccion_ganadera',setProdGan],['costos_ganaderos',setCostosGan],['ventas_ganaderas',setVentasGan]];
  const res=await Promise.all(qs.map(([t])=>supabase.from(t).select('*').eq('empresa_id',eid).order(t==='lotes'?'nombre':'created_at',{ascending:false})));
  res.forEach((r,i)=>qs[i][1](r.data||[])); if(!campaniaId&&res[0].data?.[0])setCampaniaId(res[0].data[0].id); if(!loteId&&res[1].data?.[0])setLoteId(res[1].data[0].id);
 }
 async function crearEmpresa(){let {data,error}=await supabase.from('empresas').insert(empresa).select().single(); if(error)return setMsg(error.message); await supabase.from('usuarios_empresa').insert({user_id:session.user.id,empresa_id:data.id,email:session.user.email,nombre:session.user.email,rol:'admin'}); setEmpresaId(data.id);setMsg('Empresa creada.');cargar();}
 async function insertar(t,p,ok){if(!empresaId&&t!=='empresas')return setMsg('Primero creá o seleccioná una empresa.');let {error}=await supabase.from(t).insert(p); if(error)return setMsg(error.message); setMsg(ok);cargar();}
 async function borrar(t,id){if(!confirm('¿Seguro que querés borrar este dato?'))return;let {error}=await supabase.from(t).delete().eq('id',id); if(error)return setMsg(error.message); setMsg('Dato borrado.');setEdit(null);cargar();}
 async function guardarEdicion(){const {tabla,row}=edit, limpio={...row}; ['id','created_at','updated_at','empresa_id','creado_por'].forEach(k=>delete limpio[k]); let {error}=await supabase.from(tabla).update(limpio).eq('id',row.id); if(error)return setMsg(error.message); setMsg('Dato actualizado.');setEdit(null);cargar();}
 const stockInsumos=useMemo(()=>insumos.map(i=>({...i,stock_actual:movInsumos.filter(m=>m.insumo_id===i.id).reduce((a,m)=>['compra','ajuste_positivo'].includes(m.tipo_movimiento)?a+num(m.cantidad):['salida_aplicacion','ajuste_negativo'].includes(m.tipo_movimiento)?a-num(m.cantidad):a,0)})),[insumos,movInsumos]);
 const r=useMemo(()=>{let ia=ventasAgri.reduce((a,x)=>a+num(x.ingreso_total),0), caa=costosAgri.reduce((a,x)=>a+num(x.costo_total),0), ig=ventasGan.reduce((a,x)=>a+num(x.ingreso_total),0), cgx=costosGan.reduce((a,x)=>a+num(x.costo_total),0), ci=movInsumos.filter(x=>x.tipo_movimiento==='compra').reduce((a,x)=>a+num(x.costo_total),0); return {ia,caa,ig,cgx,ci,ma:ia-caa,mg:ig-cgx,total:ia+ig-caa-cgx-ci}},[ventasAgri,costosAgri,ventasGan,costosGan,movInsumos]);
 function exportar(){const wb=XLSX.utils.book_new(); Object.entries({Empresas:empresas,Campanias:campanias,Lotes:lotes,Produccion_Agricola:prodAgri,Costos_Agricolas:costosAgri,Ventas_Agricolas:ventasAgri,Stock_Cultivos:stockCultivos,Insumos:stockInsumos,Movimientos_Insumos:movInsumos,Produccion_Ganadera:prodGan,Costos_Ganaderos:costosGan,Ventas_Ganaderas:ventasGan}).forEach(([k,v])=>XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(v),k.slice(0,31))); XLSX.writeFile(wb,'RentAgro_exportacion.xlsx')}
 if(!session)return <main className="container login-bg"><div className="brand-card"><div className="logo">🌱 Rent<span>Agro</span></div><p>Gestión agro-ganadera integral.</p></div><section className="card"><h2>Ingresar</h2><input placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)}/><input placeholder="Contraseña" type="password" value={password} onChange={e=>setPassword(e.target.value)}/><button onClick={ingresar}>Ingresar</button><button className="dark" onClick={registrar}>Crear usuario</button>{msg&&<p className="notice">{msg}</p>}</section></main>;
 return <main className="container"><header className="top hero"><div><div className="logo">🌱 Rent<span>Agro</span></div><p>{session.user.email}</p></div><button className="danger" onClick={salir}>Salir</button></header>{msg&&<p className="notice">{msg}</p>}
 <section className="card selectors"><label>Empresa activa</label><select value={empresaId} onChange={e=>setEmpresaId(e.target.value)}><option value="">Seleccionar</option>{empresas.map(x=><option key={x.id} value={x.id}>{x.nombre}</option>)}</select><label>Campaña activa</label><select value={campaniaId} onChange={e=>setCampaniaId(e.target.value)}><option value="">Seleccionar</option>{campanias.map(x=><option key={x.id} value={x.id}>{x.nombre}</option>)}</select><label>Lote activo</label><select value={loteId} onChange={e=>setLoteId(e.target.value)}><option value="">Seleccionar</option>{lotes.map(x=><option key={x.id} value={x.id}>{x.nombre}</option>)}</select></section>
 {edit&&<EditBox edit={edit} setEdit={setEdit} onSave={guardarEdicion}/>}
 <nav className="tabs">{['dashboard','alta','agricultura','insumos','ganaderia','reportes'].map(t=><button key={t} className={`${tab===t?'active':''} ${t}`} onClick={()=>setTab(t)}>{t}</button>)}<button onClick={exportar}>Exportar Excel</button></nav>
 {tab==='dashboard'&&<section><div className="grid four"><Kpi title="Ingreso agrícola" value={money(r.ia)}/><Kpi title="Costo agrícola" value={money(r.caa)}/><Kpi title="Compras insumos" value={money(r.ci)}/><Kpi title="Resultado total" value={money(r.total)}/></div><div className="grid three"><Feature className="agri-card" title="Agricultura" text="Lotes, cultivos, costos, ventas y stock."/><Feature className="gana-card" title="Ganadería" text="Producción, costos y ventas ganaderas."/><Feature className="report-card" title="Reportes" text="Informes y Excel."/></div></section>}
 {tab==='alta'&&<section><div className="grid two"><Form title="Crear empresa" data={empresa} setData={setEmpresa} fields={['nombre','pais','provincia','localidad']} onSave={crearEmpresa}/><Form title="Crear campaña" data={campania} setData={setCampania} fields={['nombre','fecha_inicio','fecha_fin','estado']} onSave={()=>insertar('campanias',{...campania,empresa_id:empresaId},'Campaña creada.')}/><Form title="Crear lote" data={lote} setData={setLote} fields={['nombre','campo','superficie_ha','provincia','localidad','tenencia','costo_alquiler_ha','cultivo_actual']} onSave={()=>insertar('lotes',{...lote,empresa_id:empresaId},'Lote creado.')}/></div><ET title="Empresas" tabla="empresas" rows={empresas} cols={['nombre','pais','provincia','localidad']} setEdit={setEdit} borrar={borrar}/><ET title="Campañas" tabla="campanias" rows={campanias} cols={['nombre','fecha_inicio','fecha_fin','estado']} setEdit={setEdit} borrar={borrar}/><ET title="Lotes" tabla="lotes" rows={lotes} cols={['nombre','campo','superficie_ha','cultivo_actual','tenencia']} setEdit={setEdit} borrar={borrar}/></section>}
 {tab==='agricultura'&&<section><div className="grid three"><Form title="Producción agrícola" data={pa} setData={setPa} fields={['fecha','cultivo','hectareas','rinde_esperado_qq_ha','rinde_real_qq_ha','toneladas','precio_estimado','observaciones']} onSave={()=>insertar('produccion_agricola',{...pa,empresa_id:empresaId,campania_id:campaniaId,lote_id:loteId,creado_por:session.user.id},'Producción guardada.')}/><Form title="Costo agrícola" data={ca} setData={setCa} fields={['fecha','cultivo','categoria','concepto','cantidad_por_ha','costo_unitario','hectareas','unidad','moneda','proveedor','forma_pago','observaciones']} onSave={()=>insertar('costos_agricolas',{...ca,tipo_costo:ca.categoria,empresa_id:empresaId,campania_id:campaniaId,lote_id:loteId,creado_por:session.user.id},'Costo guardado.')}/><Form title="Venta agrícola" data={va} setData={setVa} fields={['fecha','cultivo','cantidad','unidad','toneladas','precio','precio_tn','moneda','comprador','condicion','estado']} onSave={()=>insertar('ventas_agricolas',{...va,empresa_id:empresaId,campania_id:campaniaId,creado_por:session.user.id},'Venta guardada.')}/></div><ET title="Producción agrícola" tabla="produccion_agricola" rows={prodAgri} cols={['fecha','cultivo','hectareas','toneladas','precio_estimado']} setEdit={setEdit} borrar={borrar}/><ET title="Costos agrícolas" tabla="costos_agricolas" rows={costosAgri} cols={['fecha','cultivo','categoria','concepto','hectareas','costo_total']} setEdit={setEdit} borrar={borrar}/><ET title="Ventas agrícolas" tabla="ventas_agricolas" rows={ventasAgri} cols={['fecha','cultivo','toneladas','precio_tn','ingreso_total','comprador']} setEdit={setEdit} borrar={borrar}/></section>}
 {tab==='insumos'&&<section><div className="grid three"><Form title="Stock por cultivo" data={sc} setData={setSc} fields={['cultivo','cantidad_total','unidad','precio_promedio','observaciones']} onSave={()=>insertar('stock_cultivos',{...sc,empresa_id:empresaId,campania_id:campaniaId},'Stock por cultivo guardado.')}/><Form title="Alta insumo / agroquímico" data={insumo} setData={setInsumo} fields={['nombre','tipo','unidad','marca','proveedor','stock_minimo','observaciones']} onSave={()=>insertar('insumos',{...insumo,empresa_id:empresaId},'Insumo guardado.')}/><div className="card"><h2>Compra / Salida de insumo</h2><label>Insumo<select value={movIns.insumo_id} onChange={e=>setMovIns({...movIns,insumo_id:e.target.value})}><option value="">Seleccionar</option>{insumos.map(i=><option key={i.id} value={i.id}>{i.nombre}</option>)}</select></label><FormBody data={movIns} setData={setMovIns} fields={['fecha','tipo_movimiento','cantidad','costo_unitario','cultivo','motivo','observaciones']}/><button onClick={()=>insertar('movimientos_insumos',{...movIns,empresa_id:empresaId,campania_id:campaniaId,lote_id:loteId,creado_por:session.user.id},'Movimiento guardado.')}>Guardar movimiento</button></div></div><ET title="Stock por cultivo" tabla="stock_cultivos" rows={stockCultivos} cols={['cultivo','cantidad_total','unidad','precio_promedio']} setEdit={setEdit} borrar={borrar}/><ET title="Stock actual insumos" tabla="insumos" rows={stockInsumos} cols={['nombre','tipo','unidad','stock_actual','stock_minimo','proveedor']} setEdit={setEdit} borrar={borrar}/><ET title="Compras / Salidas" tabla="movimientos_insumos" rows={movInsumos} cols={['fecha','tipo_movimiento','cantidad','costo_unitario','costo_total','cultivo','motivo']} setEdit={setEdit} borrar={borrar}/></section>}
 {tab==='ganaderia'&&<section><div className="grid two"><Form title="Producción ganadera" data={pg} setData={setPg} fields={['fecha','categoria','potrero','cabezas','peso_inicial_kg','peso_final_kg','dias_ciclo']} onSave={()=>insertar('produccion_ganadera',{...pg,empresa_id:empresaId,campania_id:campaniaId,creado_por:session.user.id},'Producción ganadera guardada.')}/><Form title="Costo ganadero" data={cg} setData={setCg} fields={['fecha','categoria','tipo_costo','concepto','costo_total','cabezas','moneda','proveedor','observaciones']} onSave={()=>insertar('costos_ganaderos',{...cg,empresa_id:empresaId,campania_id:campaniaId,creado_por:session.user.id},'Costo ganadero guardado.')}/><Form title="Venta ganadera" data={vg} setData={setVg} fields={['fecha','categoria','cabezas','kilos_vendidos','precio_kg','comprador','comision','flete','moneda']} onSave={()=>insertar('ventas_ganaderas',{...vg,empresa_id:empresaId,campania_id:campaniaId,creado_por:session.user.id},'Venta ganadera guardada.')}/></div><ET title="Producción ganadera" tabla="produccion_ganadera" rows={prodGan} cols={['fecha','categoria','potrero','cabezas','peso_final_kg','kg_producidos']} setEdit={setEdit} borrar={borrar}/><ET title="Costos ganaderos" tabla="costos_ganaderos" rows={costosGan} cols={['fecha','categoria','tipo_costo','concepto','costo_total']} setEdit={setEdit} borrar={borrar}/><ET title="Ventas ganaderas" tabla="ventas_ganaderas" rows={ventasGan} cols={['fecha','categoria','cabezas','kilos_vendidos','precio_kg','ingreso_total']} setEdit={setEdit} borrar={borrar}/></section>}
 {tab==='reportes'&&<section className="grid two"><Report title="Resumen agrícola" items={[['Producción total',prodAgri.reduce((a,x)=>a+num(x.toneladas),0).toFixed(2)+' tn'],['Stock cultivos',stockCultivos.reduce((a,x)=>a+num(x.cantidad_total),0).toFixed(2)],['Costos agrícolas',money(r.caa)],['Ventas agrícolas',money(r.ia)],['Margen agrícola',money(r.ma)]]}/><Report title="Resumen insumos" items={[['Insumos cargados',insumos.length],['Movimientos',movInsumos.length],['Compras insumos',money(r.ci)]]}/><Report title="Resumen ganadero" items={[['Costos ganaderos',money(r.cgx)],['Ventas ganaderas',money(r.ig)],['Margen ganadero',money(r.mg)]]}/></section>}
 </main>
}
function Kpi(p){return <div className="card kpi"><p>{p.title}</p><h2>{p.value}</h2></div>}
function Feature(p){return <div className={`card feature ${p.className}`}><h2>{p.title}</h2><p>{p.text}</p></div>}
function Form({title,data,setData,fields,onSave}){return <div className="card"><h2>{title}</h2><FormBody data={data} setData={setData} fields={fields}/><button onClick={onSave}>Guardar</button></div>}
function FormBody({data,setData,fields}){return <>{fields.map(f=><label key={f}>{f.replaceAll('_',' ')}<input type={f.includes('fecha')?'date':nums.includes(f)?'number':'text'} value={data[f]??''} onChange={e=>setData({...data,[f]:e.target.value})}/></label>)}</>}
function ET({title,tabla,rows,cols,setEdit,borrar}){return <div className="card tablewrap"><h2>{title}</h2><table><thead><tr>{cols.map(c=><th key={c}>{c.replaceAll('_',' ')}</th>)}<th>Acciones</th></tr></thead><tbody>{rows.map((r,i)=><tr key={r.id||i}>{cols.map(c=><td key={c}>{String(r[c]??'')}</td>)}<td className="actions"><button className="mini secondary" onClick={()=>setEdit({tabla,row:{...r}})}>Editar</button><button className="mini danger" onClick={()=>borrar(tabla,r.id)}>Borrar</button></td></tr>)}</tbody></table></div>}
function EditBox({edit,setEdit,onSave}){const keys=Object.keys(edit.row).filter(k=>!['id','created_at','updated_at','empresa_id','creado_por'].includes(k));return <section className="card editbox"><h2>Editar / renombrar</h2><p><b>Tabla:</b> {edit.tabla}</p><div className="grid two">{keys.map(k=><label key={k}>{k.replaceAll('_',' ')}<input type={k.includes('fecha')?'date':nums.includes(k)?'number':'text'} value={edit.row[k]??''} onChange={e=>setEdit({...edit,row:{...edit.row,[k]:e.target.value}})}/></label>)}</div><button onClick={onSave}>Guardar cambios</button><button className="secondary" onClick={()=>setEdit(null)}>Cancelar</button></section>}
function Report({title,items}){return <div className="card report-card"><h2>{title}</h2>{items.map(([k,v])=><p key={k}><b>{k}:</b> {v}</p>)}</div>}
