
import { useEffect,useMemo,useState } from 'react';
import { supabase } from '../lib/supabaseClient';
import * as XLSX from 'xlsx';
const money=v=>'$'+Math.round(Number(v||0)).toLocaleString('es-AR'), num=v=>Number(v||0), today=()=>new Date().toISOString().slice(0,10);
const nums=['superficie_ha','costo_alquiler_ha','hectareas','rinde_esperado_qq_ha','rinde_real_qq_ha','toneladas','precio_estimado','cantidad_por_ha','costo_unitario','cantidad','precio','precio_tn','cabezas','peso_inicial_kg','peso_final_kg','dias_ciclo','costo_total','ingreso_total','kg_producidos','kilos_vendidos','precio_kg','comision','flete','stock_minimo','precio_promedio','cantidad_total','superficie_m2','valor_compra','gastos_escritura','remodelacion','valor_alquiler_mensual','expensas_impuestos','valor_venta_estimado','monto','precio_m2','inversion_total'];
const generatedFields=['costo_total','ingreso_total','kg_producidos','inversion_total','precio_m2'];
function limpiarPayload(obj,{editar=false}={}){
  const limpio={...obj};
  Object.keys(limpio).forEach(k=>{
    if(['id','created_at','updated_at','empresa_id','creado_por'].includes(k)||(editar&&generatedFields.includes(k))) delete limpio[k];
    else if(nums.includes(k)) limpio[k]=limpio[k]===''||limpio[k]===null||limpio[k]===undefined?0:Number(limpio[k]);
    else if((k.endsWith('_id')||k==='user_id')&&limpio[k]==='') limpio[k]=null;
    else if(k.includes('fecha')&&limpio[k]==='') limpio[k]=null;
  });
  return limpio;
}
export default function Home(){
 const [session,setSession]=useState(null),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[msg,setMsg]=useState(''),[tab,setTab]=useState('dashboard'),[edit,setEdit]=useState(null);
 const [empresaId,setEmpresaId]=useState(''),[campaniaId,setCampaniaId]=useState(''),[loteId,setLoteId]=useState('');
 const [empresas,setEmpresas]=useState([]),[campanias,setCampanias]=useState([]),[lotes,setLotes]=useState([]),[prodAgri,setProdAgri]=useState([]),[costosAgri,setCostosAgri]=useState([]),[ventasAgri,setVentasAgri]=useState([]),[stockCultivos,setStockCultivos]=useState([]),[insumos,setInsumos]=useState([]),[movInsumos,setMovInsumos]=useState([]),[prodGan,setProdGan]=useState([]),[costosGan,setCostosGan]=useState([]),[ventasGan,setVentasGan]=useState([]),[propiedades,setPropiedades]=useState([]),[costosInmo,setCostosInmo]=useState([]),[ingresosInmo,setIngresosInmo]=useState([]),[usuariosEmpresa,setUsuariosEmpresa]=useState([]);
 const [nuevoUsuario,setNuevoUsuario]=useState({email:'',nombre:'',rol:'operador',activo:true});
 const [empresa,setEmpresa]=useState({nombre:'Mi empresa',pais:'Argentina',provincia:'',localidad:''});
 const [campania,setCampania]=useState({nombre:'2025/2026',fecha_inicio:'',fecha_fin:'',estado:'activa'});
 const [lote,setLote]=useState({nombre:'Lote 1',campo:'',superficie_ha:0,provincia:'',localidad:'',tenencia:'propio',costo_alquiler_ha:0,cultivo_actual:'Soja'});
 const [pa,setPa]=useState({fecha:today(),cultivo:'Soja',hectareas:0,rinde_esperado_qq_ha:0,rinde_real_qq_ha:0,toneladas:0,precio_estimado:0,observaciones:''});
 const [ca,setCa]=useState({fecha:today(),cultivo:'Soja',categoria:'Herbicida',concepto:'',cantidad_por_ha:0,costo_unitario:0,hectareas:0,unidad:'lt',moneda:'ARS',proveedor:'',forma_pago:'',observaciones:''});
 const [va,setVa]=useState({fecha:today(),cultivo:'Soja',cantidad:0,unidad:'tn',toneladas:0,precio:0,precio_tn:0,moneda:'ARS',comprador:'',condicion:'',estado:'pendiente'});
 const [sc,setSc]=useState({cultivo:'Soja',cantidad_total:0,unidad:'tn',precio_promedio:0,observaciones:''});
 const [insumo,setInsumo]=useState({nombre:'',tipo:'Herbicida',unidad:'litros',marca:'',proveedor:'',stock_minimo:0,observaciones:''});
 const [movIns,setMovIns]=useState({fecha:today(),insumo_id:'',tipo_movimiento:'compra',cantidad:0,costo_unitario:0,cultivo:'',motivo:'',observaciones:''});
 const [pg,setPg]=useState({fecha:today(),categoria:'Recría',potrero:'',cabezas:0,peso_inicial_kg:0,peso_final_kg:0,dias_ciclo:0});
 const [cg,setCg]=useState({fecha:today(),categoria:'Cría',tipo_costo:'Sanidad',concepto:'',costo_total:0,cabezas:0,moneda:'ARS',proveedor:'',observaciones:''});
 const [vg,setVg]=useState({fecha:today(),categoria:'Novillos',cabezas:0,kilos_vendidos:0,precio_kg:0,comprador:'',comision:0,flete:0,moneda:'ARS'});
 const [prop,setProp]=useState({nombre:'Propiedad 1',tipo:'Campo',provincia:'',localidad:'',direccion:'',superficie_m2:0,estado:'en análisis',valor_compra:0,gastos_escritura:0,remodelacion:0,valor_alquiler_mensual:0,expensas_impuestos:0,valor_venta_estimado:0,moneda:'ARS',observaciones:''});
 const [ci,setCi]=useState({fecha:today(),propiedad_id:'',categoria:'Mantenimiento',concepto:'',costo_total:0,moneda:'ARS',proveedor:'',observaciones:''});
 const [ii,setIi]=useState({fecha:today(),propiedad_id:'',tipo_ingreso:'Alquiler',monto:0,moneda:'ARS',cliente_inquilino:'',estado:'cobrado',observaciones:''});
 useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data.session));const {data:l}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>l.subscription.unsubscribe()},[]);
 useEffect(()=>{if(session)cargar()},[session]); useEffect(()=>{if(empresaId)cargar()},[empresaId]);
 async function ingresar(){let {error}=await supabase.auth.signInWithPassword({email,password}); setMsg(error?error.message:'Ingreso correcto.')}
 async function registrar(){let {error}=await supabase.auth.signUp({email,password}); setMsg(error?error.message:'Usuario creado. Revisá email si pide confirmación.')}
 async function salir(){await supabase.auth.signOut();setSession(null)}
 async function cargar(){
  const emp=await supabase.from('empresas').select('*').order('created_at',{ascending:false}); setEmpresas(emp.data||[]);
  const eid=empresaId||emp.data?.[0]?.id||''; if(eid&&!empresaId)setEmpresaId(eid); if(!eid)return;
  const qs=[['campanias',setCampanias],['lotes',setLotes],['produccion_agricola',setProdAgri],['costos_agricolas',setCostosAgri],['ventas_agricolas',setVentasAgri],['stock_cultivos',setStockCultivos],['insumos',setInsumos],['movimientos_insumos',setMovInsumos],['produccion_ganadera',setProdGan],['costos_ganaderos',setCostosGan],['ventas_ganaderas',setVentasGan],['propiedades_inmobiliarias',setPropiedades],['costos_inmobiliarios',setCostosInmo],['ingresos_inmobiliarios',setIngresosInmo],['usuarios_empresa',setUsuariosEmpresa]];
  const res=await Promise.all(qs.map(([t])=>supabase.from(t).select('*').eq('empresa_id',eid).order(t==='lotes'?'nombre':'created_at',{ascending:false})));
  res.forEach((r,i)=>qs[i][1](r.data||[])); if(!campaniaId&&res[0].data?.[0])setCampaniaId(res[0].data[0].id); if(!loteId&&res[1].data?.[0])setLoteId(res[1].data[0].id);
 }
 async function crearEmpresa(){let {data,error}=await supabase.from('empresas').insert(empresa).select().single(); if(error)return setMsg(error.message); await supabase.from('usuarios_empresa').insert({user_id:session.user.id,empresa_id:data.id,email:session.user.email,nombre:session.user.email,rol:'admin'}); setEmpresaId(data.id);setMsg('Empresa creada.');cargar();}
 const miUsuario=usuariosEmpresa.find(u=>u.user_id===session?.user?.id||u.email===session?.user?.email);
 const miRol=miUsuario?.rol||'admin';
 const puedeCrear=['admin','administrador','operador'].includes(miRol);
 const puedeEditar=['admin','administrador','operador'].includes(miRol);
 const puedeEliminar=['admin','administrador'].includes(miRol);
 const puedeGestionarRoles=['admin','administrador'].includes(miRol);
 async function insertar(t,p,ok){if(!puedeCrear)return setMsg('Tu rol es Consulta: solo podés ver reportes y datos.'); if(!empresaId&&t!=='empresas')return setMsg('Primero creá o seleccioná una empresa.'); const payload=limpiarPayload(p); let {error}=await supabase.from(t).insert(payload); if(error)return setMsg(error.message); setMsg(ok);cargar();}
 async function borrar(t,id){if(!puedeEliminar)return setMsg('Solo Administrador puede eliminar registros.'); if(!confirm('¿Seguro que querés borrar este dato?'))return;let {error}=await supabase.from(t).delete().eq('id',id); if(error)return setMsg(error.message); setMsg('Dato borrado.');setEdit(null);cargar();}
 async function subirImagen(file,actualizar){if(!file)return; const ext=file.name.split('.').pop(); const path=`${empresaId||'sin_empresa'}/${Date.now()}-${Math.random().toString(16).slice(2)}.${ext}`; const {error}=await supabase.storage.from('rentagro-imagenes').upload(path,file,{upsert:false}); if(error)return setMsg('Error al subir imagen: '+error.message); const {data}=supabase.storage.from('rentagro-imagenes').getPublicUrl(path); actualizar(data.publicUrl); setMsg('Imagen cargada.');}
 async function guardarEdicion(){if(!puedeEditar)return setMsg('Tu rol es Consulta: no podés editar registros.'); const {tabla,row}=edit, limpio=limpiarPayload(row,{editar:true}); let {error}=await supabase.from(tabla).update(limpio).eq('id',row.id); if(error)return setMsg(error.message); setMsg('Dato actualizado.');setEdit(null);cargar();}
 async function guardarRolUsuario(){if(!puedeGestionarRoles)return setMsg('Solo Administrador puede gestionar usuarios.'); if(!nuevoUsuario.email)return setMsg('Ingresá el email del usuario.'); const payload=limpiarPayload({...nuevoUsuario,email:nuevoUsuario.email.trim().toLowerCase(),empresa_id:empresaId}); let {error}=await supabase.from('usuarios_empresa').upsert(payload,{onConflict:'empresa_id,email'}); if(error)return setMsg(error.message); setMsg('Rol guardado.'); setNuevoUsuario({email:'',nombre:'',rol:'operador',activo:true}); cargar();}
 async function desactivarUsuario(u){if(!puedeGestionarRoles)return setMsg('Solo Administrador puede gestionar usuarios.'); if(u.email===session.user.email)return setMsg('No podés desactivarte a vos misma.'); let {error}=await supabase.from('usuarios_empresa').update({activo:false}).eq('id',u.id); if(error)return setMsg(error.message); setMsg('Usuario desactivado.'); cargar();}
 const stockInsumos=useMemo(()=>insumos.map(i=>({...i,stock_actual:movInsumos.filter(m=>m.insumo_id===i.id).reduce((a,m)=>['compra','ajuste_positivo'].includes(m.tipo_movimiento)?a+num(m.cantidad):['salida_aplicacion','ajuste_negativo'].includes(m.tipo_movimiento)?a-num(m.cantidad):a,0)})),[insumos,movInsumos]);
 const stockAlertas=stockInsumos.filter(i=>num(i.stock_actual)<=num(i.stock_minimo));
 const r=useMemo(()=>{let ia=ventasAgri.reduce((a,x)=>a+num(x.ingreso_total),0), caa=costosAgri.reduce((a,x)=>a+num(x.costo_total),0), ig=ventasGan.reduce((a,x)=>a+num(x.ingreso_total),0), cgx=costosGan.reduce((a,x)=>a+num(x.costo_total),0), ci=movInsumos.filter(x=>x.tipo_movimiento==='compra').reduce((a,x)=>a+num(x.costo_total),0), ii=ingresosInmo.reduce((a,x)=>a+num(x.monto),0), cii=costosInmo.reduce((a,x)=>a+num(x.costo_total),0), inv=propiedades.reduce((a,x)=>a+num(x.valor_compra)+num(x.gastos_escritura)+num(x.remodelacion),0), val=propiedades.reduce((a,x)=>a+num(x.valor_venta_estimado),0); return {ia,caa,ig,cgx,ci,ii,cii,inv,val,ma:ia-caa,mg:ig-cgx,mi:ii-cii,plus:val-inv,total:ia+ig+ii-caa-cgx-ci-cii}},[ventasAgri,costosAgri,ventasGan,costosGan,movInsumos,ingresosInmo,costosInmo,propiedades]);
 function exportar(){const wb=XLSX.utils.book_new(); Object.entries({Empresas:empresas,Campanias:campanias,Lotes:lotes,Produccion_Agricola:prodAgri,Costos_Agricolas:costosAgri,Ventas_Agricolas:ventasAgri,Stock_Cultivos:stockCultivos,Insumos:stockInsumos,Movimientos_Insumos:movInsumos,Produccion_Ganadera:prodGan,Costos_Ganaderos:costosGan,Ventas_Ganaderas:ventasGan,Propiedades_Inmobiliarias:propiedades,Costos_Inmobiliarios:costosInmo,Ingresos_Inmobiliarios:ingresosInmo}).forEach(([k,v])=>XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(v),k.slice(0,31))); XLSX.writeFile(wb,'RentAgro_exportacion.xlsx')}
 if(!session)return <main className="container login-bg"><div className="brand-card"><div className="logo">🌱 Rent<span>Agro</span></div><p>Gestión agro-ganadera integral.</p></div><section className="card"><h2>Ingresar</h2><input placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)}/><input placeholder="Contraseña" type="password" value={password} onChange={e=>setPassword(e.target.value)}/><button onClick={ingresar}>Ingresar</button><button className="dark" onClick={registrar}>Crear usuario</button>{msg&&<p className="notice">{msg}</p>}</section></main>;
 return <main className="container"><header className="top hero"><div><div className="logo">🌱 Rent<span>Agro</span></div><p>{session.user.email} · Rol: <b>{miRol}</b></p></div><button className="danger" onClick={salir}>Salir</button></header>{msg&&<p className="notice">{msg}</p>}
 <section className="card selectors"><label>Empresa activa</label><select value={empresaId} onChange={e=>setEmpresaId(e.target.value)}><option value="">Seleccionar</option>{empresas.map(x=><option key={x.id} value={x.id}>{x.nombre}</option>)}</select><label>Campaña activa</label><select value={campaniaId} onChange={e=>setCampaniaId(e.target.value)}><option value="">Seleccionar</option>{campanias.map(x=><option key={x.id} value={x.id}>{x.nombre}</option>)}</select><label>Lote activo</label><select value={loteId} onChange={e=>setLoteId(e.target.value)}><option value="">Seleccionar</option>{lotes.map(x=><option key={x.id} value={x.id}>{x.nombre}</option>)}</select></section>
 {edit&&<EditBox edit={edit} setEdit={setEdit} onSave={guardarEdicion}/>}
 <nav className="tabs">{['dashboard','alta','agricultura','insumos','ganaderia','inmobiliaria','reportes',...(puedeGestionarRoles?['usuarios']:[])].map(t=><button key={t} className={`${tab===t?'active':''} ${t}`} onClick={()=>setTab(t)}>{({dashboard:'🏠 Dashboard',alta:'➕ Alta',agricultura:'🌱 Agricultura',insumos:'🧪 Insumos',ganaderia:'🐂 Ganadería',inmobiliaria:'🏡 Inmobiliaria',reportes:'📊 Reportes',usuarios:'👥 Usuarios y roles'})[t]}</button>)}<button onClick={exportar}>📥 Exportar Excel</button></nav>
 {tab==='dashboard'&&<section className="module-screen dashboard-screen"><div className="dashboard-hero card"><div><h1>Panel RentAgro</h1><p>Resumen operativo agrícola, ganadero, inmobiliario y stock.</p></div><button onClick={exportar}>Exportar Excel</button></div><div className="grid four"><Kpi title="Ingreso agrícola" value={money(r.ia)}/><Kpi title="Costo agrícola" value={money(r.caa)}/><Kpi title="Stock bajo" value={stockAlertas.length}/><Kpi title="Resultado inmobiliario" value={money(r.mi)}/><Kpi title="Resultado total" value={money(r.total)}/></div><div className="grid three"><Feature className="agri-card" title="🌱 Agricultura" text="Lotes, cultivos, costos, ventas y stock por cultivo."/><Feature className="gana-card" title="🐂 Ganadería" text="Producción, costos y ventas ganaderas."/><Feature className="inmo-card" title="🏡 Inmobiliaria" text="Propiedades, inversión, alquileres, costos y reventa."/><Feature className="report-card" title="📊 Reportes" text="Informes, KPIs y Excel."/></div>{stockAlertas.length>0&&<div className="card alerta"><h2>Alertas de stock bajo</h2>{stockAlertas.map(i=><p key={i.id}>⚠️ {i.nombre}: {i.stock_actual} {i.unidad} / mínimo {i.stock_minimo}</p>)}</div>}</section>}
 {tab==='alta'&&<section className="module-screen alta-screen"><div className="grid two"><Form title="Crear empresa" data={empresa} setData={setEmpresa} fields={['nombre','pais','provincia','localidad','imagen_url']} uploadImage={subirImagen} onSave={crearEmpresa}/><Form title="Crear campaña" data={campania} setData={setCampania} fields={['nombre','fecha_inicio','fecha_fin','estado']} onSave={()=>insertar('campanias',{...campania,empresa_id:empresaId},'Campaña creada.')}/><Form title="Crear lote" data={lote} setData={setLote} fields={['nombre','campo','superficie_ha','provincia','localidad','tenencia','costo_alquiler_ha','cultivo_actual','imagen_url']} uploadImage={subirImagen} onSave={()=>insertar('lotes',{...lote,empresa_id:empresaId},'Lote creado.')}/></div><ET title="Empresas" tabla="empresas" rows={empresas} cols={['nombre','pais','provincia','localidad']} setEdit={setEdit} borrar={borrar}/><ET title="Campañas" tabla="campanias" rows={campanias} cols={['nombre','fecha_inicio','fecha_fin','estado']} setEdit={setEdit} borrar={borrar}/><ET title="Lotes" tabla="lotes" rows={lotes} cols={['nombre','campo','superficie_ha','cultivo_actual','tenencia']} setEdit={setEdit} borrar={borrar}/></section>}
 {tab==='agricultura'&&<section className="module-screen agricultura-screen"><div className="grid three"><Form title="Producción agrícola" data={pa} setData={setPa} fields={['fecha','cultivo','hectareas','rinde_esperado_qq_ha','rinde_real_qq_ha','toneladas','precio_estimado','imagen_url','observaciones']} uploadImage={subirImagen} onSave={()=>insertar('produccion_agricola',{...pa,empresa_id:empresaId,campania_id:campaniaId,lote_id:loteId,creado_por:session.user.id},'Producción guardada.')}/><Form title="Costo agrícola" data={ca} setData={setCa} fields={['fecha','cultivo','categoria','concepto','cantidad_por_ha','costo_unitario','hectareas','unidad','moneda','proveedor','forma_pago','imagen_url','observaciones']} uploadImage={subirImagen} onSave={()=>insertar('costos_agricolas',{...ca,tipo_costo:ca.categoria,empresa_id:empresaId,campania_id:campaniaId,lote_id:loteId,creado_por:session.user.id},'Costo guardado.')}/><Form title="Venta agrícola" data={va} setData={setVa} fields={['fecha','cultivo','cantidad','unidad','toneladas','precio','precio_tn','moneda','comprador','condicion','estado','imagen_url']} uploadImage={subirImagen} onSave={()=>insertar('ventas_agricolas',{...va,empresa_id:empresaId,campania_id:campaniaId,creado_por:session.user.id},'Venta guardada.')}/></div><ET title="Producción agrícola" tabla="produccion_agricola" rows={prodAgri} cols={['fecha','cultivo','hectareas','toneladas','precio_estimado']} setEdit={setEdit} borrar={borrar}/><ET title="Costos agrícolas" tabla="costos_agricolas" rows={costosAgri} cols={['fecha','cultivo','categoria','concepto','hectareas','costo_total']} setEdit={setEdit} borrar={borrar}/><ET title="Ventas agrícolas" tabla="ventas_agricolas" rows={ventasAgri} cols={['fecha','cultivo','toneladas','precio_tn','ingreso_total','comprador']} setEdit={setEdit} borrar={borrar}/></section>}
 {tab==='insumos'&&<section className="module-screen insumos-screen"><div className="grid three"><Form title="Stock por cultivo" data={sc} setData={setSc} fields={['cultivo','cantidad_total','unidad','precio_promedio','observaciones']} onSave={()=>insertar('stock_cultivos',{...sc,empresa_id:empresaId,campania_id:campaniaId},'Stock por cultivo guardado.')}/><Form title="Alta insumo / agroquímico" data={insumo} setData={setInsumo} fields={['nombre','tipo','unidad','marca','proveedor','stock_minimo','imagen_url','observaciones']} uploadImage={subirImagen} onSave={()=>insertar('insumos',{...insumo,empresa_id:empresaId},'Insumo guardado.')}/><div className="card"><h2>Compra / Salida de insumo</h2><label>Insumo<select value={movIns.insumo_id} onChange={e=>setMovIns({...movIns,insumo_id:e.target.value})}><option value="">Seleccionar</option>{insumos.map(i=><option key={i.id} value={i.id}>{i.nombre}</option>)}</select></label><FormBody data={movIns} setData={setMovIns} fields={['fecha','tipo_movimiento','cantidad','costo_unitario','cultivo','motivo','observaciones']} uploadImage={subirImagen}/><button onClick={()=>insertar('movimientos_insumos',{...movIns,empresa_id:empresaId,campania_id:campaniaId,lote_id:loteId,creado_por:session.user.id},'Movimiento guardado.')}>Guardar movimiento</button></div></div><ET title="Stock por cultivo" tabla="stock_cultivos" rows={stockCultivos} cols={['cultivo','cantidad_total','unidad','precio_promedio']} setEdit={setEdit} borrar={borrar}/><ET title="Stock actual insumos" tabla="insumos" rows={stockInsumos} cols={['nombre','tipo','unidad','stock_actual','stock_minimo','proveedor']} setEdit={setEdit} borrar={borrar}/><ET title="Compras / Salidas" tabla="movimientos_insumos" rows={movInsumos} cols={['fecha','tipo_movimiento','cantidad','costo_unitario','costo_total','cultivo','motivo']} setEdit={setEdit} borrar={borrar}/></section>}
 {tab==='ganaderia'&&<section className="module-screen ganaderia-screen"><div className="grid two"><Form title="Producción ganadera" data={pg} setData={setPg} fields={['fecha','categoria','potrero','cabezas','peso_inicial_kg','peso_final_kg','dias_ciclo','imagen_url']} uploadImage={subirImagen} onSave={()=>insertar('produccion_ganadera',{...pg,empresa_id:empresaId,campania_id:campaniaId,creado_por:session.user.id},'Producción ganadera guardada.')}/><Form title="Costo ganadero" data={cg} setData={setCg} fields={['fecha','categoria','tipo_costo','concepto','costo_total','cabezas','moneda','proveedor','imagen_url','observaciones']} uploadImage={subirImagen} onSave={()=>insertar('costos_ganaderos',{...cg,empresa_id:empresaId,campania_id:campaniaId,creado_por:session.user.id},'Costo ganadero guardado.')}/><Form title="Venta ganadera" data={vg} setData={setVg} fields={['fecha','categoria','cabezas','kilos_vendidos','precio_kg','comprador','comision','flete','moneda','imagen_url']} uploadImage={subirImagen} onSave={()=>insertar('ventas_ganaderas',{...vg,empresa_id:empresaId,campania_id:campaniaId,creado_por:session.user.id},'Venta ganadera guardada.')}/></div><ET title="Producción ganadera" tabla="produccion_ganadera" rows={prodGan} cols={['fecha','categoria','potrero','cabezas','peso_final_kg','kg_producidos']} setEdit={setEdit} borrar={borrar}/><ET title="Costos ganaderos" tabla="costos_ganaderos" rows={costosGan} cols={['fecha','categoria','tipo_costo','concepto','costo_total']} setEdit={setEdit} borrar={borrar}/><ET title="Ventas ganaderas" tabla="ventas_ganaderas" rows={ventasGan} cols={['fecha','categoria','cabezas','kilos_vendidos','precio_kg','ingreso_total']} setEdit={setEdit} borrar={borrar}/></section>}
 {tab==='inmobiliaria'&&<section className="module-screen inmobiliaria-screen"><div className="grid three"><Form title="Crear propiedad / inversión" data={prop} setData={setProp} fields={['nombre','tipo','provincia','localidad','direccion','superficie_m2','estado','valor_compra','gastos_escritura','remodelacion','valor_alquiler_mensual','expensas_impuestos','valor_venta_estimado','moneda','imagen_url','observaciones']} uploadImage={subirImagen} onSave={()=>insertar('propiedades_inmobiliarias',{...prop,empresa_id:empresaId,creado_por:session.user.id},'Propiedad inmobiliaria guardada.')}/><div className="card"><h2>Costo inmobiliario</h2><label>Propiedad<select value={ci.propiedad_id} onChange={e=>setCi({...ci,propiedad_id:e.target.value})}><option value="">Seleccionar</option>{propiedades.map(p=><option key={p.id} value={p.id}>{p.nombre}</option>)}</select></label><FormBody data={ci} setData={setCi} fields={['fecha','categoria','concepto','costo_total','moneda','proveedor','observaciones']} uploadImage={subirImagen}/><button onClick={()=>insertar('costos_inmobiliarios',{...ci,empresa_id:empresaId,creado_por:session.user.id},'Costo inmobiliario guardado.')}>Guardar costo</button></div><div className="card"><h2>Ingreso inmobiliario</h2><label>Propiedad<select value={ii.propiedad_id} onChange={e=>setIi({...ii,propiedad_id:e.target.value})}><option value="">Seleccionar</option>{propiedades.map(p=><option key={p.id} value={p.id}>{p.nombre}</option>)}</select></label><FormBody data={ii} setData={setIi} fields={['fecha','tipo_ingreso','monto','moneda','cliente_inquilino','estado','observaciones']} uploadImage={subirImagen}/><button onClick={()=>insertar('ingresos_inmobiliarios',{...ii,empresa_id:empresaId,creado_por:session.user.id},'Ingreso inmobiliario guardado.')}>Guardar ingreso</button></div></div><div className="grid four"><Kpi title="Inversión cargada" value={money(r.inv)}/><Kpi title="Valor estimado" value={money(r.val)}/><Kpi title="Plusvalía estimada" value={money(r.plus)}/><Kpi title="Margen alquileres" value={money(r.mi)}/></div><ET title="Propiedades inmobiliarias" tabla="propiedades_inmobiliarias" rows={propiedades} cols={['nombre','tipo','localidad','superficie_m2','estado','valor_compra','valor_alquiler_mensual','valor_venta_estimado']} setEdit={setEdit} borrar={borrar}/><ET title="Costos inmobiliarios" tabla="costos_inmobiliarios" rows={costosInmo} cols={['fecha','categoria','concepto','costo_total','proveedor']} setEdit={setEdit} borrar={borrar}/><ET title="Ingresos inmobiliarios" tabla="ingresos_inmobiliarios" rows={ingresosInmo} cols={['fecha','tipo_ingreso','monto','cliente_inquilino','estado']} setEdit={setEdit} borrar={borrar}/></section>}

 {tab==='usuarios'&&puedeGestionarRoles&&<section className="module-screen usuarios-screen"><div className="card"><h2>👥 Gestión de usuarios y roles</h2><p>Asigná permisos por empresa. El usuario debe estar creado en Authentication de Supabase o registrarse desde la app.</p><div className="grid four"><label>Email<input value={nuevoUsuario.email} onChange={e=>setNuevoUsuario({...nuevoUsuario,email:e.target.value})} placeholder="usuario@email.com"/></label><label>Nombre<input value={nuevoUsuario.nombre} onChange={e=>setNuevoUsuario({...nuevoUsuario,nombre:e.target.value})} placeholder="Nombre"/></label><label>Rol<select value={nuevoUsuario.rol} onChange={e=>setNuevoUsuario({...nuevoUsuario,rol:e.target.value})}><option value="admin">Administrador</option><option value="operador">Operador</option><option value="consulta">Consulta</option></select></label><label>Activo<select value={nuevoUsuario.activo?'si':'no'} onChange={e=>setNuevoUsuario({...nuevoUsuario,activo:e.target.value==='si'})}><option value="si">Sí</option><option value="no">No</option></select></label></div><button onClick={guardarRolUsuario}>Guardar rol</button></div><div className="card tablewrap"><h2>Usuarios de la empresa</h2><table><thead><tr><th>Email</th><th>Nombre</th><th>Rol</th><th>Activo</th><th>Permisos</th><th>Acciones</th></tr></thead><tbody>{usuariosEmpresa.length===0&&<tr><td colSpan="6">Sin usuarios cargados.</td></tr>}{usuariosEmpresa.map(u=><tr key={u.id||u.email}><td>{u.email}</td><td>{u.nombre||''}</td><td><select value={u.rol||'operador'} onChange={async e=>{await supabase.from('usuarios_empresa').update({rol:e.target.value}).eq('id',u.id);cargar();}}><option value="admin">Administrador</option><option value="operador">Operador</option><option value="consulta">Consulta</option></select></td><td>{u.activo===false?'No':'Sí'}</td><td>{(u.rol==='admin'||u.rol==='administrador')?'Crear, editar, eliminar y gestionar usuarios':u.rol==='consulta'?'Solo lectura y reportes':'Crear y editar, sin eliminar usuarios'}</td><td><button className="mini danger" onClick={()=>desactivarUsuario(u)}>Desactivar</button></td></tr>)}</tbody></table></div></section>}
 {tab==='reportes'&&<section className="module-screen reportes-screen grid two"><Report title="Resumen agrícola" items={[['Producción total',prodAgri.reduce((a,x)=>a+num(x.toneladas),0).toFixed(2)+' tn'],['Stock cultivos',stockCultivos.reduce((a,x)=>a+num(x.cantidad_total),0).toFixed(2)],['Costos agrícolas',money(r.caa)],['Ventas agrícolas',money(r.ia)],['Margen agrícola',money(r.ma)]]}/><Report title="Resumen insumos" items={[['Insumos cargados',insumos.length],['Movimientos',movInsumos.length],['Compras insumos',money(r.ci)]]}/><Report title="Resumen ganadero" items={[['Costos ganaderos',money(r.cgx)],['Ventas ganaderas',money(r.ig)],['Margen ganadero',money(r.mg)]]}/><Report title="Resumen inmobiliario" items={[['Propiedades',propiedades.length],['Inversión cargada',money(r.inv)],['Valor estimado',money(r.val)],['Plusvalía estimada',money(r.plus)],['Ingresos',money(r.ii)],['Costos',money(r.cii)],['Margen',money(r.mi)]]}/></section>}
 </main>
}
function Kpi(p){return <div className="card kpi"><p>{p.title}</p><h2>{p.value}</h2></div>}
function Feature(p){return <div className={`card feature ${p.className}`}><h2>{p.title}</h2><p>{p.text}</p></div>}
function Form({title,data,setData,fields,onSave,uploadImage}){return <div className="card"><h2>{title}</h2><FormBody data={data} setData={setData} fields={fields} uploadImage={uploadImage}/><button onClick={onSave}>Guardar</button></div>}
function FormBody({data,setData,fields,uploadImage}){return <>{fields.map(f=><label key={f}>{f.replaceAll('_',' ')}{f==='observaciones'?<textarea value={data[f]??''} onChange={e=>setData({...data,[f]:e.target.value})}/>:f==='imagen_url'?<><input placeholder="URL de imagen" value={data[f]??''} onChange={e=>setData({...data,[f]:e.target.value})}/><input type="file" accept="image/*" onChange={e=>uploadImage&&uploadImage(e.target.files?.[0],url=>setData({...data,[f]:url}))}/>{data[f]&&<img className="thumb" src={data[f]} alt="Imagen cargada"/>}</>:<input type={f.includes('fecha')?'date':nums.includes(f)?'number':'text'} value={data[f]??''} onChange={e=>setData({...data,[f]:e.target.value})}/>}</label>)}</>}
function ET({title,tabla,rows,cols,setEdit,borrar}){return <div className="card tablewrap"><h2>{title}</h2><table><thead><tr>{cols.map(c=><th key={c}>{c.replaceAll('_',' ')}</th>)}<th>Acciones</th></tr></thead><tbody>{rows.length===0&&<tr><td colSpan={cols.length+1}>Sin registros cargados.</td></tr>}{rows.map((r,i)=><tr key={r.id||i}>{cols.map(c=><td key={c}>{c==='imagen_url'&&r[c]?<img className="thumb miniimg" src={r[c]} alt="Imagen"/>:String(r[c]??'')}</td>)}<td className="actions"><button type="button" title="Editar / renombrar" className="mini secondary" onClick={(e)=>{e.preventDefault();e.stopPropagation();setEdit({tabla,row:{...r}});setTimeout(()=>window.scrollTo({top:0,behavior:'smooth'}),50)}}>✏️</button><button type="button" title="Eliminar" className="mini danger" onClick={(e)=>{e.preventDefault();e.stopPropagation();borrar(tabla,r.id)}}>🗑️</button></td></tr>)}</tbody></table></div>}
function EditBox({edit,setEdit,onSave}){const keys=Object.keys(edit.row).filter(k=>!['id','created_at','updated_at','empresa_id','creado_por'].includes(k));return <div className="edit-overlay"><section className="card editbox"><div className="edit-head"><div><h2>✏️ Editar / renombrar registro</h2><p><b>Tabla:</b> {edit.tabla}</p></div><button type="button" className="secondary" onClick={()=>setEdit(null)}>Cerrar</button></div><div className="grid two">{keys.map(k=><label key={k}>{k.replaceAll('_',' ')}{k==='observaciones'?<textarea value={edit.row[k]??''} onChange={e=>setEdit({...edit,row:{...edit.row,[k]:e.target.value}})}/>:<input type={k.includes('fecha')?'date':nums.includes(k)?'number':'text'} value={edit.row[k]??''} onChange={e=>setEdit({...edit,row:{...edit.row,[k]:e.target.value}})}/>}</label>)}</div><button type="button" onClick={onSave}>Guardar cambios</button><button type="button" className="secondary" onClick={()=>setEdit(null)}>Cancelar</button></section></div>}
function Report({title,items}){return <div className="card report-card"><h2>{title}</h2>{items.map(([k,v])=><p key={k}><b>{k}:</b> {v}</p>)}</div>}
